all: main1.exe main2.exe main3.exe

main1.exe: main1.cpp
	g++ -Wall -Wpedantic -Wextra -o main1.exe -std=c++20 main1.cpp

main2.exe: main2.cpp
	g++ -Wall -Wpedantic -Wextra -o main2.exe -std=c++20 main2.cpp

main3.exe: main3.cpp
	g++ -Wall -Wpedantic -Wextra -o main3.exe -std=c++20 main3.cpp